### ISSUE TITLE
Compile fails for IMI Japanese vocabulary

### ISSUE THREAD

**Issue by sblabreu** [marcelotto/rdf-ex#4]
Hi,

Testing IMI vocabulary https://imi.ipa.go.jp/
[IRI](https://imi.ipa.go.jp/ns/core/2)

After adding IMI IC vocabulary

```
  defvocab ic,
     base_iri: "http://imi.ipa.go.jp/ns/core/rdf#",
     file: "imicore231.ttl",
     case_violations: :ignore
     # # alias: ["国": "home"]
     # # ignore: ~w[国 期間]
     # strict: false
```

Compile fails:

```
 iex -S mix
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Compiling 1 file (.ex)
Compiling vocabulary namespace for https://imi.ipa.go.jp/ns/core/2#
Compiling vocabulary namespace for http://www.w3.org/2002/07/owl#
Compiling vocabulary namespace for http://www.w3.org/2000/01/rdf-schema#
Compiling vocabulary namespace for http://www.w3.org/2001/XMLSchema#
Compiling vocabulary namespace for http://schema.org/
Compiling vocabulary namespace for http://purl.org/dc/terms/
Compiling vocabulary namespace for http://xmlns.com/foaf/0.1/
Compiling vocabulary namespace for http://imi.ipa.go.jp/ns/core/rdf#

== Compilation error in file lib/imi_vocab.ex ==
** (RDF.Namespace.InvalidTermError) The following terms contain invalid characters:

- 地理座標
- .....
- 概要

You have the following options:

- if you are in control of the vocabulary, consider renaming the resource
- define an alias with the :alias option on defvocab
- change the handling of invalid characters with the :invalid_characters option on defvocab
- ignore the resource with the :ignore option on defvocab

    lib/rdf/vocabulary_namespace.ex:338: RDF.Vocabulary.Namespace.handle_invalid_characters/3
    expanding macro: RDF.Vocabulary.Namespace.defvocab/2
    lib/imi_vocab.ex:41: ImiVocab (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_worker

```

Term does not include valid characters, which is true, possibly not passing the `Regex.match?(~r/^[a-zA-Z_]\w*$/, term)` ?

Would it be possible to validate as Unicode string ? 
or is there other options   try out the IMI vocabularies?

Thanks.

**Comment by marcelotto** [comment]
As terms will be converted to functions or module names (depending on capitalization) and non-ASCII characters are not supported by Elixir/Erlang as modules names, they are for consistency reasons not supported in RDF.ex. 

As the compiler error explains you could define aliases for those terms as described [here](https://github.com/marcelotto/rdf-ex#defining-vocabulary-namespaces). 

Finally, you'll always have the option to use the IRIs of these terms directly (without any `RDF.Vocabulary.Namespace` involved), for example via the `I` sigil.

```elixir
~I<http://imi.ipa.go.jp/ns/core/rdf#アクセス型>
```

But as this would mean a lot of duplication of the base IRI the best option however would be to define a custom function:

```elixir
@ic_base "http://imi.ipa.go.jp/ns/core/rdf#"

def ic(term), do: RDF.iri(@ic_base <> term)
```
