### ISSUE TITLE
Fix Dialyzer warning

### ISSUE THREAD

**Issue by rustra** [marcelotto/rdf-ex#5]
Hi, @marcelotto! First of all thanks for your amazing work!
I would like to know whether you have a time to look at fixing Dialyzer warning. I'll try to work on them too, but they do not really look trivial.
It could really help for projects which uses this library as dependency as its Dialyzer warning are being thrown to a project. Many thanks.

**Comment by marcelotto** [comment]
In the long term, yes, but I'm currently busy with other stuff, so I don't have time for this right now, unfortunately. But I'd happily accept a PR.

**Comment by rustra** [comment]
Thanks for the reply, @marcelotto!

**Comment by rustra** [comment]
@marcelotto Please check my PR in scope of this issue: https://github.com/marcelotto/rdf-ex/pull/6.

**Comment by marcelotto** [comment]
❤️Merged. Thank you very much again, @rustra .

**Comment by rustra** [comment]
Hi again, @marcelotto! Please look at one more MR which fixes all the rest Dialyzer warnings: https://github.com/marcelotto/rdf-ex/pull/7.
And I would like to ask you to update library version after merging it. Thanks in advance!

**Comment by marcelotto** [comment]
@rustra I've just released v0.7.1.

**Comment by rustra** [comment]
Thank you so much! 🖤
